### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by anthonysterling** [stickermule/rump#14]
Hello.

First of all, thank you very much for this. Very cool.

I noticed that there's no test coverage and, if it's okay, I'd like to add/increase that? I'm on vacation for the next fortnight, but I can get a PR in before the end of the month?

Anthony.

**Comment by nixtrace** [comment]
@anthonysterling Yes, that would be awesome!

**Comment by nixtrace** [comment]
Hi,

We just released Rump 1.0.0 with full test coverage and CI.

Thanks!
