### ISSUE TITLE
When dump data from A to B，but A has been written continuously

### ISSUE THREAD

**Issue by yangbodong22011** [stickermule/rump#17]
Hello.
thank you very much for this. Very cool.

As the title says，in this case , it will lose some keys，will you consider covering this case?

**Comment by nixtrace** [comment]
Hi,

Thanks for the comment!

Yes, this is expected and unfortunately there's no way to fix it.

The only way to make a Redis dump from a specific point in time without affecting performance is by using `BGSAVE`, disabled on ElastiCache.

Rump tries to do its best with the commands that are actually enabled on ElastiCache, without affecting the performance of the source database. :)
