### ISSUE TITLE
Unexpected element type for Strings, got type redis.Error

### ISSUE THREAD

**Issue by s4mur4i** [stickermule/rump#18]
Hy,
I have an interesting issue by some redis clusters.
We have 3 redis clusters in AWS.
Old, New1, New2
When I do sync from old to new1, then everything goes fine.
When I do sync from old to new 2 I get following error:
redigo: unexpected element type for Strings, got type redis.Error

I can log into new2 with redis-cli, so don't see what could be wrong, compared to new1. new1 and new 2 are identical clusters, same instance size, count, etc..

Thank you

**Comment by nixtrace** [comment]
Hi,

Thanks for opening the issue.

We just released Rump 1.0.0, feel free to reopen if you still see this happening.
