### ISSUE TITLE
Rump doesn't copy all keys

### ISSUE THREAD

**Issue by s4mur4i** [stickermule/rump#19]
In a test environment we did a test transfer between two redis cluster, and we found that there was a bigger number of differences between key numbers.
Dest node 1625684 
Source node 1673187

How can this happen, or how can we mitigate these issues? How can we debug what cases them?
Thank you

**Comment by nixtrace** [comment]
Hi,

Thanks for opening the issue.

This is related to the Redis `SCAN` command guarantees: https://redis.io/commands/scan#scan-guarantees

`Elements that were not constantly present in the collection during a full iteration, may be returned or not: it is undefined`
