### ISSUE TITLE
ttl support

### ISSUE THREAD

**Issue by eugenetaranov** [stickermule/rump#21]
Hello,

rump is a great tool however in certain situations having ttl set to 0 does not work okay (session data etc). May I suggest adding a separate flag for ttl with 0 default, so that default behavior does not change. Please see my local change at https://github.com/stickermule/rump/compare/master...eugenetaranov:ttl, if you find it useful, I'll be happy to make a PR.

**Comment by nixtrace** [comment]
Hi,

Thanks for opening the issue.

We just released Rump 1.0.0 with optional `-ttl` support.
