### ISSUE TITLE
Is there a docker image with rump setup?

### ISSUE THREAD

**Issue by rajeshgalla** [stickermule/rump#25]
The demo link(https://github.com/stickermule/rump#demo) contains an instance of docker image running with rump already installed. However, not able to find an image for the same online

**Comment by nixtrace** [comment]
Hi,

We just released Rump 1.0.0, it comes with a [Dockerfile.example](https://github.com/stickermule/rump/blob/master/infra/Dockerfile.example).

Thanks!
