### ISSUE TITLE
Doesnt show error if auth is enabled

### ISSUE THREAD

**Issue by trondhindenes** [stickermule/rump#26]
I just noticed that if dumping TO a cluster with AUTH enabled, and NOT specifying the auth password in the "connection string", rump will not show any error, leading the user to believe that a dump has been performed (when it in fact has not)

**Comment by nixtrace** [comment]
Hi,

We just released Rump 1.0.0 with support for Redis URIs with auth.
If you still see this happening feel free to reopen.

Thanks!
