### ISSUE TITLE
signal: exit  redis read: exit ERR Invalid TTL value, must be >= 0

### ISSUE THREAD

**Issue by allen12921** [stickermule/rump#31]
- [x] I have read the [contributing](docs/CONTRIBUTING.md) guide.

### Report
Sync with ttl terminated by 'ERR Invalid TTL value, must be >= 0'
The source AWS ElastiCache redis version is 3.2.10
rump -from redis://redis-002.ruf311.0001.cnw1.cache.amazonaws.com.cn:6379/0 -to redis://127.0.0.1:6379/0 -ttl 
signal: exit

redis read: exit
ERR Invalid TTL value, must be >= 0

**Comment by amalsom10** [comment]
While using -ttl option, please specify a TTL value

`rump -from redis://source-redis:6379/0 -to redis://destination-redis:6379/0  -ttl 1`
