### ISSUE TITLE
Deleted keys are not removed from sync endpoint

### ISSUE THREAD

**Issue by jason-yardley** [stickermule/rump#34]
- [ ] I have read the [contributing](docs/CONTRIBUTING.md) guide.

### Report

I have been using RUMP last few months to Sync a primary redis endpoint with a failover (in the even of DR). Ive noticed that RUMP is actually copying keys across and not deleted keys that have been removed from primary. For example primary endpoint has around 166 thousand keys, while the failover now has 26 million. is there a flag i am missing to do this or is it not a-part of the functionality? Thank you

**Comment by nixtrace** [comment]
Yes, Rump doesn't delete any key, it just performs a copy. Thanks!
